name: Deploy to neocities

# only run on changes to main. Use main or master depending on whatever your default branch is called.
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running the build"
        required: false
        default: "Manual build"

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fill text from snippets
        uses: Zisomerism/replace-from-file@v1.0.0
        with:
          source_dir: "templates"

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3

        with:
          find: "WORKFLOW_DATE_PLACEHOLDER"
          replace: ${{ github.event.repository.updated_at}}
          regex: false
          
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
        
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3.0.2
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          dist_dir: src
          cleanup: true
          neocities_supporter: false
          preview_before_deploy: true